// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "events",
    columns: [
      { name: "name", type: "text" },
      { name: "location", type: "text" },
      { name: "description", type: "text" },
      { name: "price", type: "int" },
      { name: "company", type: "text" },
      { name: "ID", type: "int", defaultValue: "0" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Events = InferredTypes["events"];
export type EventsRecord = Events & XataRecord;

export type DatabaseSchema = {
  events: EventsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Luckshakira-Kanana-s-workspace-6oiat3.us-west-2.xata.sh/db/XATA",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
